# Generated by Django 3.2.9 on 2021-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211113_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=10, max_digits=19),
        ),
    ]
