# Generated by Django 3.2.9 on 2021-11-14 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_products_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
