# Generated by Django 3.2.9 on 2021-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211119_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=9),
        ),
    ]
